### ISSUE TITLE
Inclusion of HLA alleles

### ISSUE THREAD

**Issue by moutsian** [dlrice/coloc#1]
It would be good to be able to filter (in or out) individuals on the basis of their imputed HLA alleles, at 2D or 4D resolution.

This will enable us to ask questions like "I want people who have at least one copy of HLA-A*01, have no copy of HLA-DRB1*11:01, and are homozygotes for SNPs varX or varY"

**Comment by dlrice** [comment]
Is there a need to select one of:

1. 2D
2. 4D
3. both

for the resolution?

**Comment by moutsian** [comment]
It should just be 2D or 4D, but this is  for each of the alleles; for instance it could be 2D for HLA -A (e.g. HLA-A*02 carriers) and at the same time carriers of HLA-DRB1*15:02 (which is at 4D resolution)

**Comment by dlrice** [comment]
We can encode:
> This will enable us to ask questions like "I want people who have at least one copy of HLA-A01, have no copy of HLA-DRB111:01, and are homozygotes for SNPs varX or varY"
as
```
include_allele = 'HLA-A01'
exclude_allele = 'HLA-DRB111:01'
```
1. Will we always have an `include_allele`? By that I mean we will never just want individuals without the `excluded_allele`?
2. There could be >1 `include_allele` (in which case it might be better to call this `include_alleles = [HLA-A01, ...]`). The same for `exclude_allele` - will we ever want to specify  >1?

**Comment by moutsian** [comment]
1: No, we may just want to exclude individuals
2: That's fine I think
